### ISSUE TITLE
pycharm debugging after switch to click

### ISSUE THREAD

**Issue by dbkeator** [incf-nidash/PyNIDM#102]
@djarecka After switching nidm_query.py to click, I can't seem to debug things in Pycharm.  I have my configuration set to run the following:

Script: nidm_query.py
Script parameters: -q sample_query.txt -nl nidm.ttl -o test.csv 
Working directory: /..../PyNIDM/nidm/experiment/tools

The debugger fails on import click even though it's an installed package.  Seems from the error there's some parent package that needs to be loaded?

Connected to pydev debugger (build 143.2370)
Traceback (most recent call last):
  File "/Applications/PyCharm 2.app/Contents/helpers/pydev/pydevd.py", line 2411, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm 2.app/Contents/helpers/pydev/pydevd.py", line 1802, in run
    launch(file, globals, locals)  # execute the script
  File "/Applications/PyCharm 2.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "nidm_query.py", line 40, in <module>
    import click
  File "/Applications/PyCharm 2.app/Contents/helpers/pydev/pydev_monkey_qt.py", line 71, in patched_import
    return original_import(name, *args, **kwargs)
  File "/Users/dbkeator/Documents/Coding/PyNIDM/nidm/experiment/tools/click.py", line 2, in <module>
    from .click_base import cli
  File "/Applications/PyCharm 2.app/Contents/helpers/pydev/pydev_monkey_qt.py", line 71, in patched_import
    return original_import(name, *args, **kwargs)
SystemError: Parent module '' not loaded, cannot perform relative import

**Comment by dbkeator** [comment]
@djarecka The error above is related to your tools/click.py having relative imports.

fix:
click.py: 
from nidm.experiment.tools.click_base import cli

The next problem, PyCharm was complaining about no attribute group in click which comes from toos/click_base.py.  I think it's related to having a click.py in the tools directory which overloads the click library (see [https://github.com/pallets/click/issues/4](url))....working on a fix....

**Comment by djarecka** [comment]
@dbkeator - so we don't want to use any relative paths?

**Comment by djarecka** [comment]
@dbkeator  - the link doesn't work for me. I didn't have problems with it, but can rename `click.py`
