### ISSUE TITLE
PyDOT package new installation

### ISSUE THREAD

**Issue by dnkennedy** [incf-nidash/PyNIDM#115]
When testing the csv2nidm instructions, I get the following error: (mac OSX 10.12.6 (16G1510)); following instructions at: https://docs.google.com/document/d/1N_olJLBHW2WarKpu73PwGdmCS83d57iMZDI662fXZuc/edit#

Writing NIDM file...
Traceback (most recent call last):
  File "/Users/davidkennedy/anaconda/envs/pynidm_py3/lib/python3.7/site-packages/pydot.py", line 1915, in create
    working_dir=tmp_dir,
  File "/Users/davidkennedy/anaconda/envs/pynidm_py3/lib/python3.7/site-packages/pydot.py", line 136, in call_graphviz
    **kwargs
  File "/Users/davidkennedy/anaconda/envs/pynidm_py3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/davidkennedy/anaconda/envs/pynidm_py3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidkennedy/anaconda/envs/pynidm_py3/bin/csv2nidm", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/davidkennedy/simple_annotate/PyNIDM/bin/CSV2NIDM", line 7, in <module>
    main(sys.argv)
  File "/Users/davidkennedy/simple_annotate/PyNIDM/nidm/experiment/tools/CSV2NIDM.py", line 266, in main
    project.save_DotGraph(str(args.output_file + ".png"), format="png")
  File "/Users/davidkennedy/simple_annotate/PyNIDM/nidm/experiment/Core.py", line 348, in save_DotGraph
    dot.write(filename,format=format)
  File "/Users/davidkennedy/anaconda/envs/pynidm_py3/lib/python3.7/site-packages/pydot.py", line 1817, in write
    s = self.create(prog, format, encoding=encoding)
  File "/Users/davidkennedy/anaconda/envs/pynidm_py3/lib/python3.7/site-packages/pydot.py", line 1922, in create
    raise OSError(*args)
FileNotFoundError: [Errno 2] "dot" not found in path.

**Comment by dbkeator** [comment]
@djarecka Kennedy.Dave never installed PyNIDM before and followed the installation instructions.  It appears pydot isn't working?  Do you know what this error might mean?
