### ISSUE TITLE
missing "tabulate" library after pip install e .

### ISSUE THREAD

**Issue by dbkeator** [incf-nidash/PyNIDM#191]
Hi @albertcrowley,
I tried the installation instructions.  In my new conda environment after "pip install -e ." I receive the following error even though this package has been added to nidm/version.py INSTALL_REQUIRES.  If I instead run "python setup.py install" everything is ok.  So, how do we edit the installation files to get "pip install -e ." working again?

(pynidm_py3) [~/Documents/Coding/PyNIDM]$ pynidm
Traceback (most recent call last):
  File "/Users/dbkeator/opt/anaconda3/envs/pynidm_py3/bin/pynidm", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/dbkeator/opt/anaconda3/envs/pynidm_py3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/Users/dbkeator/opt/anaconda3/envs/pynidm_py3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/Users/dbkeator/opt/anaconda3/envs/pynidm_py3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/dbkeator/opt/anaconda3/envs/pynidm_py3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/Users/dbkeator/opt/anaconda3/envs/pynidm_py3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/dbkeator/opt/anaconda3/envs/pynidm_py3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tabulate' distribution was not found and is required by pynidm

**Comment by albertcrowley** [comment]
I tried to replicate this in a few different clean docker files (stock Ubuntu, stock Python, my dev docker) but I couldn't get the error.  I don't have a mac to test on and I'm thinking that might be where you saw it.

When you saw the error, had you created a new conda environment before running the pip install -e ?  Or were you re-using an existing conda env?  
When I tried the install in a clean conda environment, the last line of output is "successfully installed" packages. Tabulate isn't in that list, but in the one before that, the "successfully build" packages did have tabulate near the end of that list.  If you can recreate this, do you see tabulate in the list of built packages?
