### ISSUE TITLE
participant.tsv column name breaks NIDM conversion/serialization

### ISSUE THREAD

**Issue by mih** [incf-nidash/PyNIDM#59]
I pointed `BIDSMRI2NIDM.py` randomly to ds000200 from OpenFMRI. It seems it cannot handles spaces in column names.

Presumable cause:
```
% python -c 'print(repr(open("participants.tsv").readlines()[0]))'
'participant_id\tMnExposition\tage\tgender\tObvolume_mm3\tId12items\tavg_rating\tBOLD in VOI Olf\tnotes\n'
```

Log of explosion:

```
% ~/hacking/PyNIDM/nidm/experiment/tools/BIDSMRI2NIDM.py -d . -o please.ttl
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
Converting subject: 2001
Converting subject: 2002
Converting subject: 2003
Converting subject: 2004
Converting subject: 2005
Converting subject: 2006
Converting subject: 2007
Converting subject: 2008
Converting subject: 2009
Converting subject: 2010
Converting subject: 2011
Converting subject: 2012
Converting subject: 2013
Converting subject: 2014
Serializing NIDM graph and creating graph visualization..
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
http://bids.neuroimaging.io/BOLD in VOI Olf does not look like a valid URI, trying to serialize this will break.
Traceback (most recent call last):
  File "/home/mih/hacking/PyNIDM/nidm/experiment/tools/BIDSMRI2NIDM.py", line 318, in <module>
    main(sys.argv[1:])
  File "/home/mih/hacking/PyNIDM/nidm/experiment/tools/BIDSMRI2NIDM.py", line 313, in main
    f.write(project.serializeTurtle())
  File "/home/mih/hacking/PyNIDM/nidm/experiment/Core.py", line 300, in serializeTurtle
    return self.graph.serialize(None, format='rdf', rdf_format='ttl')
  File "/home/mih/env/datalad3-dev/lib/python3.6/site-packages/prov/model.py", line 2388, in serialize
    serializer.serialize(stream, **args)
  File "/home/mih/env/datalad3-dev/lib/python3.6/site-packages/prov/serializers/provrdf.py", line 111, in serialize
    container.serialize(buf, **newargs)
  File "/home/mih/env/datalad3-dev/lib/python3.6/site-packages/rdflib/graph.py", line 947, in serialize
    serializer.serialize(stream, base=base, encoding=encoding, **args)
  File "/home/mih/env/datalad3-dev/lib/python3.6/site-packages/rdflib/plugins/serializers/turtle.py", line 232, in serialize
    if self.statement(subject) and not firstTime:
  File "/home/mih/env/datalad3-dev/lib/python3.6/site-packages/rdflib/plugins/serializers/turtle.py", line 293, in statement
    return self.s_squared(subject) or self.s_default(subject)
  File "/home/mih/env/datalad3-dev/lib/python3.6/site-packages/rdflib/plugins/serializers/turtle.py", line 298, in s_default
    self.predicateList(subject)
  File "/home/mih/env/datalad3-dev/lib/python3.6/site-packages/rdflib/plugins/serializers/turtle.py", line 400, in predicateList
    self.verb(predicate, newline=True)
  File "/home/mih/env/datalad3-dev/lib/python3.6/site-packages/rdflib/plugins/serializers/turtle.py", line 404, in verb
    self.path(node, VERB, newline)
  File "/home/mih/env/datalad3-dev/lib/python3.6/site-packages/rdflib/plugins/serializers/turtle.py", line 312, in path
    or self.p_default(node, position, newline)):
  File "/home/mih/env/datalad3-dev/lib/python3.6/site-packages/rdflib/plugins/serializers/turtle.py", line 318, in p_default
    self.write(self.label(node, position))
  File "/home/mih/env/datalad3-dev/lib/python3.6/site-packages/rdflib/plugins/serializers/turtle.py", line 334, in label
    return self.getQName(node, position == VERB) or node.n3()
  File "/home/mih/env/datalad3-dev/lib/python3.6/site-packages/rdflib/term.py", line 247, in n3
    raise Exception('"%s" does not look like a valid URI, I cannot serialize this as N3/Turtle. Perhaps you wanted to urlencode it?'%self)
Exception: "http://bids.neuroimaging.io/BOLD in VOI Olf" does not look like a valid URI, I cannot serialize this as N3/Turtle. Perhaps you wanted to urlencode it?
```

**Comment by dbkeator** [comment]
Give it another try, should be fixed now....
